name: Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # This might take a few minutes, but it frees up ~30GB
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Scan image for vulnerabilities
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: 'docker.io/my-organization/my-app:${{ github.sha }}'
          fail-build: true
          severity-cutoff: high
          output-format: sarif
        env:
          GRYPE_DB_MAX_ALLOWED_BUILT_AGE: "2160h"

      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
